/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BettingHistoryRouteImport } from './routes/betting.history'
import { Route as BettingDashboardRouteImport } from './routes/betting.dashboard'
import { Route as BettingDetailsIdRouteImport } from './routes/betting.details.$id'

const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BettingHistoryRoute = BettingHistoryRouteImport.update({
  id: '/betting/history',
  path: '/betting/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BettingDashboardRoute = BettingDashboardRouteImport.update({
  id: '/betting/dashboard',
  path: '/betting/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BettingDetailsIdRoute = BettingDetailsIdRouteImport.update({
  id: '/betting/details/$id',
  path: '/betting/details/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/onboarding': typeof OnboardingRoute
  '/reset': typeof ResetRoute
  '/betting/dashboard': typeof BettingDashboardRoute
  '/betting/history': typeof BettingHistoryRoute
  '/betting/details/$id': typeof BettingDetailsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/onboarding': typeof OnboardingRoute
  '/reset': typeof ResetRoute
  '/betting/dashboard': typeof BettingDashboardRoute
  '/betting/history': typeof BettingHistoryRoute
  '/betting/details/$id': typeof BettingDetailsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/onboarding': typeof OnboardingRoute
  '/reset': typeof ResetRoute
  '/betting/dashboard': typeof BettingDashboardRoute
  '/betting/history': typeof BettingHistoryRoute
  '/betting/details/$id': typeof BettingDetailsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/mfa'
    | '/onboarding'
    | '/reset'
    | '/betting/dashboard'
    | '/betting/history'
    | '/betting/details/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/mfa'
    | '/onboarding'
    | '/reset'
    | '/betting/dashboard'
    | '/betting/history'
    | '/betting/details/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/mfa'
    | '/onboarding'
    | '/reset'
    | '/betting/dashboard'
    | '/betting/history'
    | '/betting/details/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MfaRoute: typeof MfaRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetRoute: typeof ResetRoute
  BettingDashboardRoute: typeof BettingDashboardRoute
  BettingHistoryRoute: typeof BettingHistoryRoute
  BettingDetailsIdRoute: typeof BettingDetailsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betting/history': {
      id: '/betting/history'
      path: '/betting/history'
      fullPath: '/betting/history'
      preLoaderRoute: typeof BettingHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betting/dashboard': {
      id: '/betting/dashboard'
      path: '/betting/dashboard'
      fullPath: '/betting/dashboard'
      preLoaderRoute: typeof BettingDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betting/details/$id': {
      id: '/betting/details/$id'
      path: '/betting/details/$id'
      fullPath: '/betting/details/$id'
      preLoaderRoute: typeof BettingDetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MfaRoute: MfaRoute,
  OnboardingRoute: OnboardingRoute,
  ResetRoute: ResetRoute,
  BettingDashboardRoute: BettingDashboardRoute,
  BettingHistoryRoute: BettingHistoryRoute,
  BettingDetailsIdRoute: BettingDetailsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
