/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentsWalletsRouteImport } from './routes/payments.wallets'
import { Route as PaymentsSettlementsRouteImport } from './routes/payments.settlements'
import { Route as PaymentsHistoryRouteImport } from './routes/payments.history'
import { Route as PaymentsDashboardRouteImport } from './routes/payments.dashboard'
import { Route as KycPendingRouteImport } from './routes/kyc.pending'
import { Route as KycAllRouteImport } from './routes/kyc.all'
import { Route as KycIdRouteImport } from './routes/kyc.$id'
import { Route as BettingHistoryRouteImport } from './routes/betting.history'
import { Route as BettingDashboardRouteImport } from './routes/betting.dashboard'
import { Route as PaymentsTransactionsIdRouteImport } from './routes/payments.transactions.$id'
import { Route as BettingDetailsIdRouteImport } from './routes/betting.details.$id'

const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsWalletsRoute = PaymentsWalletsRouteImport.update({
  id: '/payments/wallets',
  path: '/payments/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsSettlementsRoute = PaymentsSettlementsRouteImport.update({
  id: '/payments/settlements',
  path: '/payments/settlements',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsHistoryRoute = PaymentsHistoryRouteImport.update({
  id: '/payments/history',
  path: '/payments/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsDashboardRoute = PaymentsDashboardRouteImport.update({
  id: '/payments/dashboard',
  path: '/payments/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KycPendingRoute = KycPendingRouteImport.update({
  id: '/kyc/pending',
  path: '/kyc/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const KycAllRoute = KycAllRouteImport.update({
  id: '/kyc/all',
  path: '/kyc/all',
  getParentRoute: () => rootRouteImport,
} as any)
const KycIdRoute = KycIdRouteImport.update({
  id: '/kyc/$id',
  path: '/kyc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BettingHistoryRoute = BettingHistoryRouteImport.update({
  id: '/betting/history',
  path: '/betting/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BettingDashboardRoute = BettingDashboardRouteImport.update({
  id: '/betting/dashboard',
  path: '/betting/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsTransactionsIdRoute = PaymentsTransactionsIdRouteImport.update({
  id: '/payments/transactions/$id',
  path: '/payments/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BettingDetailsIdRoute = BettingDetailsIdRouteImport.update({
  id: '/betting/details/$id',
  path: '/betting/details/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/onboarding': typeof OnboardingRoute
  '/reset': typeof ResetRoute
  '/betting/dashboard': typeof BettingDashboardRoute
  '/betting/history': typeof BettingHistoryRoute
  '/kyc/$id': typeof KycIdRoute
  '/kyc/all': typeof KycAllRoute
  '/kyc/pending': typeof KycPendingRoute
  '/payments/dashboard': typeof PaymentsDashboardRoute
  '/payments/history': typeof PaymentsHistoryRoute
  '/payments/settlements': typeof PaymentsSettlementsRoute
  '/payments/wallets': typeof PaymentsWalletsRoute
  '/betting/details/$id': typeof BettingDetailsIdRoute
  '/payments/transactions/$id': typeof PaymentsTransactionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/onboarding': typeof OnboardingRoute
  '/reset': typeof ResetRoute
  '/betting/dashboard': typeof BettingDashboardRoute
  '/betting/history': typeof BettingHistoryRoute
  '/kyc/$id': typeof KycIdRoute
  '/kyc/all': typeof KycAllRoute
  '/kyc/pending': typeof KycPendingRoute
  '/payments/dashboard': typeof PaymentsDashboardRoute
  '/payments/history': typeof PaymentsHistoryRoute
  '/payments/settlements': typeof PaymentsSettlementsRoute
  '/payments/wallets': typeof PaymentsWalletsRoute
  '/betting/details/$id': typeof BettingDetailsIdRoute
  '/payments/transactions/$id': typeof PaymentsTransactionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/onboarding': typeof OnboardingRoute
  '/reset': typeof ResetRoute
  '/betting/dashboard': typeof BettingDashboardRoute
  '/betting/history': typeof BettingHistoryRoute
  '/kyc/$id': typeof KycIdRoute
  '/kyc/all': typeof KycAllRoute
  '/kyc/pending': typeof KycPendingRoute
  '/payments/dashboard': typeof PaymentsDashboardRoute
  '/payments/history': typeof PaymentsHistoryRoute
  '/payments/settlements': typeof PaymentsSettlementsRoute
  '/payments/wallets': typeof PaymentsWalletsRoute
  '/betting/details/$id': typeof BettingDetailsIdRoute
  '/payments/transactions/$id': typeof PaymentsTransactionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/mfa'
    | '/onboarding'
    | '/reset'
    | '/betting/dashboard'
    | '/betting/history'
    | '/kyc/$id'
    | '/kyc/all'
    | '/kyc/pending'
    | '/payments/dashboard'
    | '/payments/history'
    | '/payments/settlements'
    | '/payments/wallets'
    | '/betting/details/$id'
    | '/payments/transactions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/mfa'
    | '/onboarding'
    | '/reset'
    | '/betting/dashboard'
    | '/betting/history'
    | '/kyc/$id'
    | '/kyc/all'
    | '/kyc/pending'
    | '/payments/dashboard'
    | '/payments/history'
    | '/payments/settlements'
    | '/payments/wallets'
    | '/betting/details/$id'
    | '/payments/transactions/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/mfa'
    | '/onboarding'
    | '/reset'
    | '/betting/dashboard'
    | '/betting/history'
    | '/kyc/$id'
    | '/kyc/all'
    | '/kyc/pending'
    | '/payments/dashboard'
    | '/payments/history'
    | '/payments/settlements'
    | '/payments/wallets'
    | '/betting/details/$id'
    | '/payments/transactions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MfaRoute: typeof MfaRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetRoute: typeof ResetRoute
  BettingDashboardRoute: typeof BettingDashboardRoute
  BettingHistoryRoute: typeof BettingHistoryRoute
  KycIdRoute: typeof KycIdRoute
  KycAllRoute: typeof KycAllRoute
  KycPendingRoute: typeof KycPendingRoute
  PaymentsDashboardRoute: typeof PaymentsDashboardRoute
  PaymentsHistoryRoute: typeof PaymentsHistoryRoute
  PaymentsSettlementsRoute: typeof PaymentsSettlementsRoute
  PaymentsWalletsRoute: typeof PaymentsWalletsRoute
  BettingDetailsIdRoute: typeof BettingDetailsIdRoute
  PaymentsTransactionsIdRoute: typeof PaymentsTransactionsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/wallets': {
      id: '/payments/wallets'
      path: '/payments/wallets'
      fullPath: '/payments/wallets'
      preLoaderRoute: typeof PaymentsWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/settlements': {
      id: '/payments/settlements'
      path: '/payments/settlements'
      fullPath: '/payments/settlements'
      preLoaderRoute: typeof PaymentsSettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/history': {
      id: '/payments/history'
      path: '/payments/history'
      fullPath: '/payments/history'
      preLoaderRoute: typeof PaymentsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/dashboard': {
      id: '/payments/dashboard'
      path: '/payments/dashboard'
      fullPath: '/payments/dashboard'
      preLoaderRoute: typeof PaymentsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc/pending': {
      id: '/kyc/pending'
      path: '/kyc/pending'
      fullPath: '/kyc/pending'
      preLoaderRoute: typeof KycPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc/all': {
      id: '/kyc/all'
      path: '/kyc/all'
      fullPath: '/kyc/all'
      preLoaderRoute: typeof KycAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc/$id': {
      id: '/kyc/$id'
      path: '/kyc/$id'
      fullPath: '/kyc/$id'
      preLoaderRoute: typeof KycIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betting/history': {
      id: '/betting/history'
      path: '/betting/history'
      fullPath: '/betting/history'
      preLoaderRoute: typeof BettingHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betting/dashboard': {
      id: '/betting/dashboard'
      path: '/betting/dashboard'
      fullPath: '/betting/dashboard'
      preLoaderRoute: typeof BettingDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/transactions/$id': {
      id: '/payments/transactions/$id'
      path: '/payments/transactions/$id'
      fullPath: '/payments/transactions/$id'
      preLoaderRoute: typeof PaymentsTransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betting/details/$id': {
      id: '/betting/details/$id'
      path: '/betting/details/$id'
      fullPath: '/betting/details/$id'
      preLoaderRoute: typeof BettingDetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MfaRoute: MfaRoute,
  OnboardingRoute: OnboardingRoute,
  ResetRoute: ResetRoute,
  BettingDashboardRoute: BettingDashboardRoute,
  BettingHistoryRoute: BettingHistoryRoute,
  KycIdRoute: KycIdRoute,
  KycAllRoute: KycAllRoute,
  KycPendingRoute: KycPendingRoute,
  PaymentsDashboardRoute: PaymentsDashboardRoute,
  PaymentsHistoryRoute: PaymentsHistoryRoute,
  PaymentsSettlementsRoute: PaymentsSettlementsRoute,
  PaymentsWalletsRoute: PaymentsWalletsRoute,
  BettingDetailsIdRoute: BettingDetailsIdRoute,
  PaymentsTransactionsIdRoute: PaymentsTransactionsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
